### PR TITLE
cli: remove tailing / from url

### PR DESCRIPTION
**Pull request by makefu**
if the URL contains a / at the end, every request results in 404 from
bepasty server side. rstrip removes this character if exists.

If merged with list-pastes, the line must become part of main, not upload :)

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
are we fixing this at the right place?
should it maybe get fixed in the server?

**Comment by makefu** [comment]
well, my assumption is that the server is picky in regards to paths.

Even though on unix `//` is equal to `/` it is not necessarily like this on webservers.
According to RFC-2396 every slash is significant (https://www.ietf.org/rfc/rfc2396.txt ).

**Comment by makefu** [comment]
@ThomasWaldmann @NotANormalNerd any objections regarding this feature? if not then i would merge it into master.

After that i would publish the last version in pypi and package it for nixos.

**Comment by NotANormalNerd** [comment]
This is something that is implemented in the server.
You have have both. Please have a look at flask's url building, what actually is preffered.

**Comment by makefu** [comment]
@NotANormalNerd so, has it actually been implemented in the server?

**Comment by NotANormalNerd** [comment]
Has been implemented by #17

**Comment by makefu** [comment]
thanks 👍

**Pull request closed without merging**
